<template>
  <v-app>
    <!-- Sidebar (Left Drawer) -->
    <v-navigation-drawer app>
  <v-img src="../assets/images/Cnlogo.png" style="width: 209px;
height: 117px;
gap: 0px;
opacity: 0px;
" />
      <v-list>
        <v-list-item>
       <v-list-item-title>Team</v-list-item-title>
       </v-list-item>
    
    <v-list-item :class="{'active-item': activeSection === 'invoices'}" @click="setActiveSection('invoices')" >
      <v-list-item-title>Invoices</v-list-item-title>
    </v-list-item>

      </v-list>
      <div class="text-center my-4 logout-user-button">
        <v-btn @click="logoutUser">Logout</v-btn>
      </div>
    </v-navigation-drawer>

    <v-main class="vue-main-page-dashboard">
      <div style="height: 50px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
     <div class="page-heading"> Invoice List</div>
    </div>

        <v-row v-if="activeSection === 'invoices'" align="center" justify="space-between" class="mb-4 mt-2">
          <v-col cols="12" md="6">
            <v-select
              v-model="selectedFilter"
              :items="filterOptions"
              label="Generated by Filter"
              outlined
            />
          </v-col>
          <v-col cols="12" md="6" class="d-flex justify-end">
            <v-btn color="primary" @click="createInvoice">Create Invoice</v-btn>
          </v-col>
        </v-row>

        <v-row class="my-4">
          <v-col cols="12" md="4" class="align-center pa-0" @click="filterTableData('all')">
            <div class="summary-box summary-box-border-right" :class="{ 'selected-card': selectedCard === 'all' }">
              <div class="summary-title">{{ totalRecords }}</div>
              <div class="summary-subtitle">Total</div>
            </div>
          </v-col>

          <v-col cols="12" md="4" class="align-center pa-0" @click="filterTableData('User')">
            <div class="summary-box summary-box-border-right" :class="{ 'selected-card': selectedCard === 'User' }">
              <div class="summary-title">{{ userGeneratedCount }}</div>
              <div class="summary-subtitle">User Generated</div>
            </div>
          </v-col>

          <v-col cols="12" md="4" class="align-center pa-0" @click="filterTableData('Panel')">
            <div class="summary-box" :class="{ 'selected-card': selectedCard === 'Panel' }">
              <div class="summary-title">{{ panelGeneratedCount }}</div>
              <div class="summary-subtitle">Panel Generated</div>
            </div>
          </v-col>
        </v-row>

      <!-- Data Table -->
        <table class="custom-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Initiated On</th>
              <th>Generated By</th>
              <th>Customer Name</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(item, index) in filteredTableData" :key="index">
              <td>{{ item.id }}</td>
              <td>{{ item.initiatedOn }}</td>
              <td>{{ item.generatedBy }}</td>
              <td>{{ item.customerName }}</td>
              <td>
                <v-btn class="edit-button" small @click="editItem(item)">Edit</v-btn>
              </td>
            </tr>
          </tbody>
        </table>
    </v-main>
  </v-app>
</template>

<script>

export default {
  name: "Dash-Board",
  components: {
  },
  data() {
    return {
      selectedFilter: "all", 
      filterOptions: ["User Generated", "Panel Generated", "All"],
      activeSection: "invoices", 
       selectedCard: "all",
      tableData: [
        {
          id: 2,
          initiatedOn: "05 Mar 2022 07:30 AM",
          generatedBy: "User",
          customerName: "Abhishek Dewangan (9877746789)",
        },
        {
          id: 1,
          initiatedOn: "04 Mar 2022 03:35 PM",
          generatedBy: "Panel",
          customerName: "Narayan Dewangan (9876789765)",
        },
      ],
      filteredTableData: [], // To store filtered data
    };
  },
  computed: {
    totalRecords() {
      return this.tableData.length;
    },
    userGeneratedCount() {
      return this.tableData.filter((item) => item.generatedBy === "User").length;
    },
    panelGeneratedCount() {
      return this.tableData.filter((item) => item.generatedBy === "Panel").length;
    },
  },
  methods: {
    logoutUser() {
      console.log("user-loggedout-from-dashboard-click");
      this.$store.dispatch("logout");
      this.$router.push("/");
    },
    createInvoice() {
      console.log("Create Invoice clicked");
      this.$router.push({ name: "addinvoice" });
    },
    setActiveSection(section) {
      this.activeSection = section;
      this.filterTableData("all"); // Reset filter when changing sections
    },
    filterTableData(filter) {
      this.selectedCard = filter;
      if (filter === "all") {
        this.filteredTableData = this.tableData; // Show all data if "all" or no filter selected
      } else {
        this.filteredTableData = this.tableData.filter((item) => item.generatedBy === filter);
      }
    },
    editItem(item) {
      console.log("Edit Item:", item);
    }
  },
  mounted() {
    this.filterTableData(this.selectedFilter);
  },
};
</script>

<style scoped>

.logout-user-button {
  position: absolute;
  top: 75%;
  left: 5rem;
  border: 1px solid red; 
  color: red;
  background-color: transparent; 
  font-weight: bold;
}
.selected-card {
  background-color: #2F80ED; 
  color: white; 
}
.edit-button {
  border: 1px solid #2F80ED; 
  color: #2F80ED;
  background-color: transparent; 
  font-weight: bold;
  text-transform: none;
  padding: 4px 8px;
}

/* Table Styles */

.custom-table {
  width: 100%;
  border-collapse: collapse;
  text-align: left;
  margin-top: 10px;
}
.custom-table th, .custom-table td {
  padding: 10px;
  text-align: center;
}

.custom-table th {
  background-color: #CBE0EF;
}

/* Table styles */

.active-item {
  background-color: #2F80ED;
  color: white;
}

.summary-box {
  text-align: center;
  cursor: pointer;
  transition: box-shadow 0.3s;
  height: 100px;
  padding: 10px;
}

.summary-box:hover {
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
}
.summary-title {
  font-size: 24px;
  font-weight: 500;
  line-height: 30px;
  text-align: left;
  padding-left: 20px;
  text-underline-position: from-font;
  text-decoration-skip-ink: none;

}
.vue-main-page-dashboard{
   margin-top: 15px;
}
.summary-subtitle {
  font-size: 16px;
  font-weight: 600;
  line-height: 20px;
  text-align: left;
  padding-left: 20px;
}
.pa-0 {
  padding: 0 !important;
}
.v-navigation-drawer {
  position: relative;
  padding-top: 50px;
}
.summary-box-border-right {
  border-right: 1px solid #ccc;
}
.page-heading{
  padding-left: 20px;
  font-weight: 600;
  padding-top: 5px;
}
</style>